//! Transparent proxying: nftables ruleset, policy routing, and a revert
//! watchdog.
//!
//! ## Provenance
//!
//! The rule structure here follows Passwall2's `nftables.sh`, which has been
//! debugged against real routers for years. Where this file departs from it,
//! the comment says why. Nothing is copied verbatim -- this generates its own
//! ruleset -- but the *technique* is theirs, and the non-obvious parts (reply
//! handling, socket matching being TCP-only, priority placement) came from
//! reading it rather than from first principles.
//!
//! ## Scope
//!
//! Intercepts TCP and UDP originating on the LAN interfaces and hands it to
//! Xray's TPROXY inbound. Traffic generated by the router itself is **not**
//! intercepted; that needs an `output` chain plus a `nat` REDIRECT path with
//! its own loop-avoidance, and leaving it out is what holds this to two short
//! chains.
//!
//! ## Why it cannot loop
//!
//! Xray's own connection to the remote server must never be re-intercepted, or
//! every packet recurses until the router dies. Three independent guards:
//!
//! 1. Reply packets of established flows return early (`ct direction reply`).
//! 2. Xray marks its outbound sockets with [`XRAY_MARK`], and marked packets
//!    return before the tproxy rules.
//! 3. The resolved address of the active server is in the bypass set.
//!
//! ## Safety
//!
//! [`Watchdog`] reverts the ruleset unless the panel confirms within a
//! deadline. A ruleset that black-holes traffic would otherwise leave the
//! router unreachable until someone power-cycles it.

use std::io::Write;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Condvar, Mutex};
use std::thread;
use std::time::{Duration, Instant};

/// Our nftables table. Separate from `fw4`, so a firewall reload cannot clobber
/// it -- and so `nft delete table` is a complete, precise revert.
pub const TABLE: &str = "xrayop";

/// Mark applied to intercepted packets, matched by the `ip rule`.
pub const PACKET_MARK: u32 = 0x1ee;
/// Mark Xray sets on its own outbound sockets so they bypass interception.
/// Passwall2 uses 255 for the same purpose; keeping the value identical means
/// the two cannot silently disagree if they ever run side by side.
pub const XRAY_MARK: u32 = 255;
/// Routing table holding the `local default dev lo` entry.
///
/// Deliberately NOT 999. Passwall2 uses table 999, and `revert` flushes this
/// table -- which runs at the start of every `apply` and from the watchdog. On
/// a router where both are installed (the expected state during migration)
/// sharing the number would delete Passwall2's local route while its nft rules
/// still marked packets, black-holing a working tunnel instantly.
pub const ROUTE_TABLE: u32 = 494;
/// Explicit `ip rule` priority. Without one the kernel picks a slot just below
/// the main table and the ordering relative to other rules becomes luck.
/// Below Passwall2's 999 so ours is consulted first when both exist.
pub const RULE_PRIORITY: u32 = 494;

/// Destinations that must never be tunnelled.
///
/// `0.0.0.0/8` matters as much as the private ranges: DHCP happens before a
/// client has an address, and tunnelling it would stop the LAN getting leases.
const BYPASS4: &[&str] = &[
    "0.0.0.0/8",
    "10.0.0.0/8",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "224.0.0.0/4",
    "240.0.0.0/4",
    // Special-purpose ranges the mature rulesets all carry. Tunnelling them is
    // pointless today; 198.18.0.0/15 matters the day FakeDNS is added, since
    // that is the conventional pool for synthetic addresses.
    "192.0.0.0/24",
    "192.0.2.0/24",
    "192.31.196.0/24",
    "192.52.193.0/24",
    "192.88.99.0/24",
    "192.175.48.0/24",
    "198.18.0.0/15",
    "198.51.100.0/24",
    "203.0.113.0/24",
];

const BYPASS6: &[&str] = &["::1/128", "fc00::/7", "fe80::/10", "ff00::/8"];

/// Everything needed to render and apply a ruleset.
#[derive(Debug, Clone)]
pub struct Plan {
    /// Xray's TPROXY inbound port.
    pub port: u16,
    /// Interfaces whose traffic is intercepted, e.g. `br-lan`.
    pub lan_interfaces: Vec<String>,
    /// Resolved addresses of the active server, added to the bypass sets.
    pub server_ips: Vec<std::net::IpAddr>,
    /// Whether to tunnel IPv6 as well as IPv4.
    pub tunnel_ipv6: bool,
}

impl Plan {
    fn bypass(&self, v6: bool) -> Vec<String> {
        let base = if v6 { BYPASS6 } else { BYPASS4 };
        let mut v: Vec<String> = base.iter().map(|s| s.to_string()).collect();
        v.extend(
            self.server_ips
                .iter()
                .filter(|ip| ip.is_ipv6() == v6)
                .map(|ip| ip.to_string()),
        );
        v
    }
}

/// Renders the nftables ruleset.
///
/// Rule order is load-bearing. Reading the `intercept` chain top to bottom:
/// replies leave first, then anything Xray itself sent, then addresses that
/// must stay direct, then anything that did not come from the LAN. Only what
/// survives all of that is handed to Xray.
pub fn build_ruleset(plan: &Plan) -> String {
    let mark = format!("{PACKET_MARK:#x}");
    let mut out = String::new();
    out.push_str(&format!("table inet {TABLE} {{\n"));

    out.push_str(&set_block("bypass4", "ipv4_addr", &plan.bypass(false)));
    out.push_str(&set_block("bypass6", "ipv6_addr", &plan.bypass(true)));

    // --- divert: keep established transparent flows on their socket ---
    //
    // TCP only. Passwall2's comment on the equivalent rule reads "Only TCP, UDP
    // Invalid" -- `socket transparent` does not reliably match UDP, and adding
    // udp here matches nothing while looking like it works. UDP is covered by
    // the `ct direction reply` rule below instead.
    out.push_str("\tchain divert {\n");
    out.push_str(&format!(
        "\t\tmeta l4proto tcp socket transparent 1 counter meta mark set {mark} accept\n"
    ));
    out.push_str("\t}\n\n");

    // --- intercept ---
    out.push_str("\tchain intercept {\n");

    out.push_str("\t\t# Replies belong to a flow xray already owns.\n");
    out.push_str("\t\tct direction reply counter return\n\n");

    // Kept as an explicit statement of intent, though it cannot match here:
    // Xray's socket mark only exists on router-originated packets, which
    // traverse `output`, not `prerouting`. The real guard against recursion is
    // structural -- this chain never sees the router's own traffic at all.
    // Passwall2 places the equivalent rule only in its OUTPUT chains.
    out.push_str("\t\t# Xray's own outbound, should output interception ever be added.\n");
    out.push_str(&format!("\t\tmeta mark {XRAY_MARK} counter return\n\n"));

    // Covers the LAN IP, the WAN IP and loopback, and keeps covering them
    // after a WAN re-DHCP -- stronger than a static set of addresses, which
    // has to be refreshed on every interface event.
    out.push_str("\t\t# Anything addressed to this router: SSH, LuCI, the panel, DNS.\n");
    out.push_str("\t\tfib daddr type { local, broadcast, anycast, multicast } counter return\n\n");

    out.push_str("\t\t# Loopback, LAN, multicast, and the proxy server itself.\n");
    out.push_str("\t\tip daddr @bypass4 counter return\n");
    out.push_str("\t\tip6 daddr @bypass6 counter return\n\n");

    let ifaces = plan
        .lan_interfaces
        .iter()
        .map(|i| format!("\"{i}\""))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str("\t\t# Only intercept what the LAN sent us.\n");
    out.push_str(&format!("\t\tiifname != {{ {ifaces} }} counter return\n\n"));

    // The mark must be set *before* tproxy in the same rule: tproxy assigns the
    // packet to the local socket, and the `ip rule` lookup that delivers it
    // there reads the mark. Passwall2 emits them in this order too.
    //
    // `tproxy ip to :PORT` keeps the original destination address and only
    // redirects the port, which is what lets xray's dokodemo-door recover where
    // the client was actually going.
    out.push_str("\t\t# Hand the rest to xray.\n");
    for proto in ["tcp", "udp"] {
        out.push_str(&format!(
            "\t\tmeta nfproto ipv4 meta l4proto {proto} counter meta mark set {mark} tproxy ip to :{} accept\n",
            plan.port
        ));
    }
    if plan.tunnel_ipv6 {
        for proto in ["tcp", "udp"] {
            out.push_str(&format!(
                "\t\tmeta nfproto ipv6 meta l4proto {proto} counter meta mark set {mark} tproxy ip6 to :{} accept\n",
                plan.port
            ));
        }
    }
    out.push_str("\t}\n\n");

    // --- base chain ---
    //
    // `mangle - 1` runs ahead of fw4's own mangle chains, so interception is
    // decided before anything else can rewrite or drop the packet.
    out.push_str("\tchain prerouting {\n");
    out.push_str("\t\ttype filter hook prerouting priority mangle - 1; policy accept;\n");
    out.push_str("\t\tcounter jump divert\n");
    out.push_str("\t\tmeta l4proto { tcp, udp } counter jump intercept\n");
    out.push_str("\t}\n\n");

    // --- input guard ---
    //
    // Xray's TPROXY inbound binds 0.0.0.0, so a LAN client can dial it
    // directly. `followRedirect` then reads the original destination as the
    // router's own address on this very port, routing sends it to `direct`,
    // and Xray connects to itself -- once per iteration, until the router runs
    // out of file descriptors. TPROXY-delivered packets keep their real
    // destination port (443, 53, ...), so only genuine direct hits match here.
    out.push_str("\tchain input_guard {\n");
    out.push_str("\t\ttype filter hook input priority filter - 1; policy accept;\n");
    out.push_str(&format!(
        "\t\tiifname != \"lo\" meta l4proto {{ tcp, udp }} th dport {} ct state new counter reject\n",
        plan.port
    ));
    out.push_str("\t}\n}\n");

    out
}

fn set_block(name: &str, kind: &str, elements: &[String]) -> String {
    let mut s = format!("\tset {name} {{\n\t\ttype {kind}\n\t\tflags interval\n\t\tauto-merge\n");
    if !elements.is_empty() {
        s.push_str(&format!("\t\telements = {{ {} }}\n", elements.join(", ")));
    }
    s.push_str("\t}\n\n");
    s
}

/// The `ip rule` / `ip route` entries that deliver marked packets to the local
/// TPROXY socket instead of forwarding them.
/// `route replace` rather than `route add`: if an earlier revert was
/// interrupted the route may still exist, and `add` would fail with EEXIST and
/// abort the whole apply.
fn route_args(plan: &Plan) -> Vec<Vec<String>> {
    let a = |s: String| s.split(' ').map(String::from).collect::<Vec<_>>();
    let mut cmds = vec![
        a(format!(
            "-4 rule add fwmark {PACKET_MARK} table {ROUTE_TABLE} priority {RULE_PRIORITY}"
        )),
        a(format!(
            "-4 route replace local 0.0.0.0/0 dev lo table {ROUTE_TABLE}"
        )),
    ];
    if plan.tunnel_ipv6 {
        cmds.push(a(format!(
            "-6 rule add fwmark {PACKET_MARK} table {ROUTE_TABLE} priority {RULE_PRIORITY}"
        )));
        cmds.push(a(format!(
            "-6 route replace local ::/0 dev lo table {ROUTE_TABLE}"
        )));
    }
    cmds
}

/// Whether Passwall2's nftables table is currently loaded.
///
/// Both projects register a base chain at `prerouting mangle - 1` and both
/// install a `local default dev lo` route. Which tproxy fires first then
/// depends on kernel registration order, and each one's divert chain re-marks
/// the other's flows. That is not a supportable state, so we refuse to apply
/// rather than produce an outage nobody can diagnose.
pub fn passwall2_active() -> bool {
    run(
        "nft",
        &[
            "list".into(),
            "table".into(),
            "inet".into(),
            "passwall2".into(),
        ],
    )
    .is_ok()
}

/// Validates the ruleset against the running kernel without applying it.
///
/// `nft --check` parses and verifies every expression -- including whether this
/// kernel supports `socket transparent`, `fib` and `tproxy` -- but commits
/// nothing. This is the only way to exercise the ruleset on a live router
/// without risking connectivity.
pub fn check(plan: &Plan) -> Result<(), String> {
    nft(&["--check", "--file", "-"], &build_ruleset(plan)).map(|_| ())
}

/// Applies the ruleset and policy routing.
///
/// Reverts on any failure, so a partial apply can never leave the router
/// marking packets with no route to carry them.
pub fn apply(plan: &Plan) -> Result<(), String> {
    if plan.lan_interfaces.is_empty() {
        // Would render `iifname != {  }`, which nft rejects with a confusing
        // parse error rather than saying what is actually wrong.
        return Err("no LAN interface configured".into());
    }
    if passwall2_active() {
        return Err(
            "Passwall2 is running and also manages transparent proxying. \
             Stop it first: /etc/init.d/passwall2 stop"
                .into(),
        );
    }
    check(plan).map_err(|e| format!("ruleset rejected: {e}"))?;

    // Start clean; applying twice must not stack duplicate rules.
    revert(plan);

    nft(&["--file", "-"], &build_ruleset(plan)).map_err(|e| format!("cannot load ruleset: {e}"))?;

    for args in route_args(plan) {
        if let Err(e) = run("ip", &args) {
            revert(plan);
            return Err(format!("cannot set up policy routing: {e}"));
        }
    }
    Ok(())
}

/// Removes everything [`apply`] installed.
///
/// Safe when nothing is installed, and never fails -- a revert that gives up
/// halfway is worse than one that pushes through.
pub fn revert(_plan: &Plan) {
    let _ = run(
        "nft",
        &["delete".into(), "table".into(), "inet".into(), TABLE.into()],
    );
    for family in ["-4", "-6"] {
        // Rules can accumulate if an earlier revert was interrupted; delete
        // until the kernel says there are none left.
        for _ in 0..4 {
            let deleted = run(
                "ip",
                &[
                    family.into(),
                    "rule".into(),
                    "del".into(),
                    "fwmark".into(),
                    PACKET_MARK.to_string(),
                    "table".into(),
                    ROUTE_TABLE.to_string(),
                ],
            );
            if deleted.is_err() {
                break;
            }
        }
        // Delete precisely the route we added. `route flush table N` would
        // remove every route in the table regardless of owner -- which is how
        // an earlier version of this file would have wiped Passwall2's routing
        // when the two shared a table number.
        let default = if family == "-4" { "0.0.0.0/0" } else { "::/0" };
        let _ = run(
            "ip",
            &[
                family.into(),
                "route".into(),
                "del".into(),
                "local".into(),
                default.into(),
                "dev".into(),
                "lo".into(),
                "table".into(),
                ROUTE_TABLE.to_string(),
            ],
        );
    }
}

/// Whether our table is currently loaded.
pub fn is_applied() -> bool {
    run(
        "nft",
        &["list".into(), "table".into(), "inet".into(), TABLE.into()],
    )
    .is_ok()
}

fn nft(args: &[&str], stdin: &str) -> Result<String, String> {
    let mut child = Command::new("nft")
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| match e.kind() {
            std::io::ErrorKind::NotFound => "nft is not installed".to_string(),
            _ => format!("cannot run nft: {e}"),
        })?;

    child
        .stdin
        .take()
        .ok_or("cannot open nft stdin")?
        .write_all(stdin.as_bytes())
        .map_err(|e| format!("cannot write to nft: {e}"))?;

    let out = child
        .wait_with_output()
        .map_err(|e| format!("nft did not finish: {e}"))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
    }
}

fn run(program: &str, args: &[String]) -> Result<(), String> {
    let out = Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .output()
        .map_err(|e| format!("cannot run {program}: {e}"))?;
    if out.status.success() {
        Ok(())
    } else {
        Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
    }
}

/// Reverts the transparent-proxy rules unless disarmed in time.
///
/// The panel arms this before applying and disarms it once the browser has
/// round-tripped a confirmation. If the new ruleset breaks connectivity, that
/// confirmation never arrives and the router heals itself.
#[derive(Clone)]
pub struct Watchdog {
    /// Bumped on every arm and disarm. A timer whose generation is stale does
    /// nothing, which makes re-arming and cancelling the same operation.
    generation: Arc<AtomicU64>,
    /// True while a timer is pending. Tracked separately rather than inferred
    /// from the generation's parity, which was wrong for arm-then-arm.
    armed: Arc<AtomicBool>,
    /// Lets `disarm` wake a sleeping timer instead of leaving it to sleep out
    /// its full duration. Without this, repeatedly enabling and disabling
    /// leaves a thread parked for 90 seconds behind each click.
    wake: Arc<(Mutex<u64>, Condvar)>,
}

impl Default for Watchdog {
    fn default() -> Self {
        Self {
            generation: Arc::new(AtomicU64::new(0)),
            armed: Arc::new(AtomicBool::new(false)),
            wake: Arc::new((Mutex::new(0), Condvar::new())),
        }
    }
}

impl Watchdog {
    pub fn new() -> Self {
        Self::default()
    }

    /// Schedules `on_timeout` to run after `after` unless disarmed first.
    pub fn arm<F>(&self, after: Duration, on_timeout: F)
    where
        F: FnOnce() + Send + 'static,
    {
        let mine = self.generation.fetch_add(1, Ordering::SeqCst) + 1;
        self.armed.store(true, Ordering::SeqCst);

        let generation = Arc::clone(&self.generation);
        let armed = Arc::clone(&self.armed);
        let wake = Arc::clone(&self.wake);

        thread::spawn(move || {
            let (lock, cv) = &*wake;
            let deadline = Instant::now() + after;
            let mut guard = lock.lock().unwrap_or_else(|e| e.into_inner());
            loop {
                // Superseded or cancelled: nothing to do.
                if generation.load(Ordering::SeqCst) != mine {
                    return;
                }
                let Some(remaining) = deadline.checked_duration_since(Instant::now()) else {
                    break;
                };
                if remaining.is_zero() {
                    break;
                }
                let (g, _) = cv
                    .wait_timeout(guard, remaining)
                    .unwrap_or_else(|e| e.into_inner());
                guard = g;
            }
            drop(guard);

            if generation.load(Ordering::SeqCst) == mine {
                armed.store(false, Ordering::SeqCst);
                on_timeout();
            }
        });
    }

    pub fn disarm(&self) {
        self.generation.fetch_add(1, Ordering::SeqCst);
        self.armed.store(false, Ordering::SeqCst);
        let (lock, cv) = &*self.wake;
        let mut n = lock.lock().unwrap_or_else(|e| e.into_inner());
        *n += 1;
        cv.notify_all();
    }

    /// Whether a timer is currently pending.
    pub fn is_armed(&self) -> bool {
        self.armed.load(Ordering::SeqCst)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::AtomicBool;

    fn plan() -> Plan {
        Plan {
            port: 12345,
            lan_interfaces: vec!["br-lan".into()],
            server_ips: vec!["203.0.113.7".parse().unwrap()],
            tunnel_ipv6: false,
        }
    }

    fn index_of(rules: &str, needle: &str) -> usize {
        rules
            .find(needle)
            .unwrap_or_else(|| panic!("missing rule: {needle}"))
    }

    #[test]
    fn server_address_is_bypassed() {
        assert!(
            build_ruleset(&plan()).contains("203.0.113.7"),
            "the proxy server must be bypassed or traffic to it loops"
        );
    }

    #[test]
    fn dhcp_and_private_ranges_are_bypassed() {
        let rules = build_ruleset(&plan());
        for net in ["0.0.0.0/8", "192.168.0.0/16", "127.0.0.0/8", "224.0.0.0/4"] {
            assert!(rules.contains(net), "{net} must be bypassed");
        }
    }

    /// Every guard has to precede the tproxy statements, or the thing it guards
    /// against gets intercepted anyway.
    #[test]
    fn guards_precede_interception() {
        let r = build_ruleset(&plan());
        let tproxy = index_of(&r, "tproxy ip to");
        for guard in [
            "ct direction reply counter return",
            "meta mark 255 counter return",
            "fib daddr type { local, broadcast, anycast, multicast } counter return",
            "ip daddr @bypass4 counter return",
            "iifname != ",
        ] {
            assert!(index_of(&r, guard) < tproxy, "{guard} must come before tproxy");
        }
    }

    /// Xray's TPROXY inbound binds 0.0.0.0, so without this a LAN client can
    /// dial it directly and make Xray connect to itself in a loop.
    #[test]
    fn direct_hits_on_the_tproxy_port_are_rejected() {
        let r = build_ruleset(&plan());
        assert!(r.contains("chain input_guard"));
        assert!(r.contains("th dport 12345 ct state new counter reject"));
        assert!(
            r.contains("iifname != \"lo\""),
            "loopback must stay allowed or xray cannot reach itself"
        );
    }

    #[test]
    fn special_purpose_ranges_are_bypassed() {
        let r = build_ruleset(&plan());
        // 198.18.0.0/15 is the conventional FakeDNS pool; the rest are
        // documentation and benchmarking ranges nothing should tunnel.
        for net in ["198.18.0.0/15", "192.0.2.0/24", "203.0.113.0/24", "192.88.99.0/24"] {
            assert!(r.contains(net), "{net} must be bypassed");
        }
    }

    /// Sharing a routing table with Passwall2 and then flushing it is how an
    /// earlier version of this file would have taken down a working tunnel.
    #[test]
    fn routing_does_not_collide_with_passwall2() {
        assert_ne!(ROUTE_TABLE, 999, "999 is Passwall2's table");
        assert_ne!(RULE_PRIORITY, 999, "999 is Passwall2's rule priority");
    }

    #[test]
    fn routes_are_added_idempotently() {
        let rule = route_args(&plan())[1].join(" ");
        assert!(
            rule.contains("route replace"),
            "an interrupted revert leaves the route behind; `add` would then fail with EEXIST"
        );
    }

    #[test]
    fn empty_interface_list_is_rejected_before_nft_sees_it() {
        let mut p = plan();
        p.lan_interfaces.clear();
        let err = apply(&p).unwrap_err();
        assert!(err.contains("LAN interface"), "got: {err}");
    }

    /// Reply packets must leave before anything else looks at them.
    #[test]
    fn replies_are_released_first() {
        let r = build_ruleset(&plan());
        let reply = index_of(&r, "ct direction reply");
        let chain = index_of(&r, "chain intercept");
        let next = index_of(&r, "meta mark 255");
        assert!(chain < reply && reply < next);
    }

    /// `socket transparent` does not reliably match UDP. Listing udp there
    /// matches nothing while looking like it works; UDP replies are handled by
    /// `ct direction reply` instead.
    #[test]
    fn socket_match_is_tcp_only() {
        let r = build_ruleset(&plan());
        let line = r
            .lines()
            .find(|l| l.contains("socket transparent"))
            .expect("divert rule");
        assert!(line.contains("meta l4proto tcp"), "got: {line}");
        assert!(!line.contains("udp"), "got: {line}");
    }

    /// The mark drives the `ip rule` lookup that delivers the packet, so it has
    /// to be set before tproxy runs, in the same rule.
    #[test]
    fn mark_is_set_before_tproxy() {
        let r = build_ruleset(&plan());
        let line = r
            .lines()
            .find(|l| l.contains("tproxy ip to"))
            .expect("tproxy rule");
        let mark = line.find("meta mark set").expect("mark statement");
        let tproxy = line.find("tproxy").expect("tproxy statement");
        assert!(mark < tproxy, "got: {line}");
    }

    /// `tproxy ip to :PORT` keeps the original destination; naming an address
    /// would throw away where the client was actually going.
    #[test]
    fn tproxy_preserves_the_original_destination() {
        let r = build_ruleset(&plan());
        assert!(r.contains("tproxy ip to :12345"));
        assert!(!r.contains("tproxy ip to 127.0.0.1"));
    }

    /// Running at plain `mangle` would race fw4's own chains at that priority.
    #[test]
    fn base_chain_runs_before_fw4_mangle() {
        assert!(build_ruleset(&plan())
            .contains("type filter hook prerouting priority mangle - 1; policy accept;"));
    }

    #[test]
    fn traffic_to_the_router_itself_is_never_intercepted() {
        assert!(
            build_ruleset(&plan()).contains("fib daddr type { local, broadcast, anycast, multicast }"),
            "without this, SSH and the panel go through the tunnel"
        );
    }

    #[test]
    fn only_lan_interfaces_are_intercepted() {
        let mut p = plan();
        p.lan_interfaces = vec!["br-lan".into(), "br-guest".into()];
        assert!(build_ruleset(&p).contains("iifname != { \"br-lan\", \"br-guest\" } counter return"));
    }

    #[test]
    fn ipv6_is_left_alone_by_default() {
        let r = build_ruleset(&plan());
        assert!(!r.contains("tproxy ip6"), "IPv6 must not be tunnelled unless asked");
        assert!(r.contains("ip6 daddr @bypass6"), "but it still needs its bypass set");
    }

    #[test]
    fn ipv6_can_be_enabled() {
        let mut p = plan();
        p.tunnel_ipv6 = true;
        p.server_ips.push("2001:db8::1".parse().unwrap());
        let r = build_ruleset(&p);
        assert!(r.contains("tproxy ip6 to :12345"));
        assert!(r.contains("2001:db8::1"));
    }

    #[test]
    fn marks_are_distinct() {
        assert_ne!(
            PACKET_MARK, XRAY_MARK,
            "xray's own traffic is identified by its mark differing from intercepted traffic"
        );
    }

    #[test]
    fn ip_rule_has_an_explicit_priority() {
        let args = route_args(&plan());
        let rule = args[0].join(" ");
        assert!(rule.contains(&format!("priority {RULE_PRIORITY}")), "got: {rule}");
    }

    #[test]
    fn ipv6_routing_is_only_added_when_tunnelled() {
        assert_eq!(route_args(&plan()).len(), 2);
        let mut p = plan();
        p.tunnel_ipv6 = true;
        assert_eq!(route_args(&p).len(), 4);
    }

    #[test]
    fn watchdog_fires_when_not_disarmed() {
        let fired = Arc::new(AtomicBool::new(false));
        let flag = Arc::clone(&fired);
        let wd = Watchdog::new();
        wd.arm(Duration::from_millis(60), move || {
            flag.store(true, Ordering::SeqCst)
        });
        assert!(wd.is_armed());
        thread::sleep(Duration::from_millis(220));
        assert!(fired.load(Ordering::SeqCst), "an unconfirmed apply must revert");
    }

    #[test]
    fn watchdog_does_not_fire_after_disarm() {
        let fired = Arc::new(AtomicBool::new(false));
        let flag = Arc::clone(&fired);
        let wd = Watchdog::new();
        wd.arm(Duration::from_millis(80), move || {
            flag.store(true, Ordering::SeqCst)
        });
        wd.disarm();
        assert!(!wd.is_armed());
        thread::sleep(Duration::from_millis(240));
        assert!(!fired.load(Ordering::SeqCst), "a confirmed apply must be kept");
    }

    /// Re-arming must cancel the previous timer, not leave two racing.
    #[test]
    fn rearming_supersedes_the_previous_timer() {
        let count = Arc::new(AtomicU64::new(0));
        let wd = Watchdog::new();
        for _ in 0..3 {
            let c = Arc::clone(&count);
            wd.arm(Duration::from_millis(80), move || {
                c.fetch_add(1, Ordering::SeqCst);
            });
        }
        thread::sleep(Duration::from_millis(280));
        assert_eq!(count.load(Ordering::SeqCst), 1, "only the newest timer may fire");
    }
}
